// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ephxvnoufczdeewpeydn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwaHh2bm91ZmN6ZGVld3BleWRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODYzMzEsImV4cCI6MjA1ODk2MjMzMX0.Ng9J9xjuuro_9IZJJTzynArqzt_OuSyCuS08woyfZUk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);